---
template: native
provider: provider-template
major-version: 0
providerDefaultBranch: main
publishRegistry: false
providerVersion: github.com/Cogni-AI-OU/pulumi-provider-template/provider.Version
parallel: 3
sdkModuleDir: sdk/go/pulumi-provider-template
esc:
  enabled: false
