// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/Cogni-AI-OU/pulumi-provider-template/sdk/go/pulumi-provider-template/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

func GetItsasecret(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "provider-boilerplate:itsasecret")
}
